import type { RunInstructionRule } from "@/lib/run-instruction-config";

export const EASY_RUN_INSTRUCTION_RULES: RunInstructionRule[] = [
    {
        id: "easy-run-start",
        message: "This is your warm up. Start easy and relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["easy"],
        phaseLabels: ["WARM UP"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "easy-run-main",
        message: "Now settle into your easy run. Keep it light and comfortable.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["easy"],
        phaseLabels: ["RUN"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "easy-run-halfway",
        message: "You are doing well. Just keep going easy.",
        priority: 190,
        triggerOn: ["periodic", "manual"],
        templateIds: ["easy"],
        minDistanceProgress: 45,
        maxDistanceProgress: 60,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "easy-run-finish",
        message: "Almost done. Stay relaxed and finish easy.",
        priority: 195,
        triggerOn: ["periodic", "manual"],
        templateIds: ["easy"],
        minDistanceProgress: 85,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "easy-run-cooldown",
        message: "Now slow down. Let your body relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["easy"],
        phaseLabels: ["SLOW DOWN", "COOL DOWN"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
];
