import type { RunInstructionRule } from "@/lib/run-instruction-config";

export const LONG_RUN_INSTRUCTION_RULES: RunInstructionRule[] = [
    {
        id: "long-run-start",
        message: "This is your warm up. Start easy and relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["long"],
        phaseLabels: ["WARM UP"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "long-run-main",
        message: "Now settle into your long run. Keep it easy and steady.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["long"],
        phaseLabels: ["ENDURANCE"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "long-run-halfway",
        message: "You are doing well. Keep going one step at a time.",
        priority: 190,
        triggerOn: ["periodic", "manual"],
        templateIds: ["long"],
        minDistanceProgress: 45,
        maxDistanceProgress: 60,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "long-run-finish",
        message: "Almost done. Stay calm and keep moving.",
        priority: 195,
        triggerOn: ["periodic", "manual"],
        templateIds: ["long"],
        minDistanceProgress: 85,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "long-run-cooldown",
        message: "Now slow down. Let your body relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["long"],
        phaseLabels: ["COOL DOWN", "SLOW DOWN"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
];
