import type { RunInstructionRule } from "@/lib/run-instruction-config";

export const POWER_WALK_INSTRUCTION_RULES: RunInstructionRule[] = [
    {
        id: "power-walk-week-1-start",
        message: "We will start with the warm up phase. The goal is to warm up your body. Walk at your normal pace.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["WARM UP"],
        minWeek: 1,
        maxWeek: 1,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-week-2-start",
        message: "We will start with the warm up phase. Walk easy. We will go a little faster soon.",
        priority: 215,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["WARM UP"],
        minWeek: 2,
        maxWeek: 2,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-early-start",
        message: "This is the warm up phase. Walk easy and relax your body.",
        priority: 210,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["WARM UP"],
        minWeek: 1,
        maxWeek: 4,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-mid-start",
        message: "This is the warm up phase. Keep it easy and relax your shoulders.",
        priority: 205,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["WARM UP"],
        minWeek: 5,
        maxWeek: 8,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-late-start",
        message: "This is the warm up phase. Settle in and keep it easy.",
        priority: 200,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["WARM UP"],
        minWeek: 9,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-main-week-1",
        message: "Now walk a little faster than normal. It should feel brisk, not hard.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["POWER WALK"],
        minWeek: 1,
        maxWeek: 1,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-main-week-2",
        message: "Now start your brisk walk. Stay in control.",
        priority: 215,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["POWER WALK"],
        minWeek: 2,
        maxWeek: 2,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-main-early",
        message: "This is the main part. Walk faster, swing your arms, and stand tall.",
        priority: 210,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["POWER WALK"],
        minWeek: 1,
        maxWeek: 4,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-main-mid",
        message: "Find your brisk pace now. Keep it smooth and steady.",
        priority: 205,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["POWER WALK"],
        minWeek: 5,
        maxWeek: 8,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-main-late",
        message: "Keep your brisk pace and hold the rhythm.",
        priority: 200,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["POWER WALK"],
        minWeek: 9,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-on-target-early",
        message: "Good. This pace is right. Keep going.",
        priority: 190,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        paceStates: ["on_target"],
        minWeek: 1,
        maxWeek: 4,
        minElapsedSec: 75,
        cooldownSec: 75,
        maxTriggers: 3,
    },
    {
        id: "power-walk-on-target-mid",
        message: "Nice. Keep this pace and stay smooth.",
        priority: 185,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        paceStates: ["on_target"],
        minWeek: 5,
        maxWeek: 8,
        minElapsedSec: 75,
        cooldownSec: 75,
        maxTriggers: 3,
    },
    {
        id: "power-walk-on-target-late",
        message: "Good rhythm. Stay with this pace.",
        priority: 180,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        paceStates: ["on_target"],
        minWeek: 9,
        minElapsedSec: 75,
        cooldownSec: 75,
        maxTriggers: 3,
    },
    {
        id: "power-walk-form-arms",
        message: "Swing your arms. They will help your pace.",
        priority: 170,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minElapsedSec: 90,
        cooldownSec: 120,
        maxTriggers: 2,
    },
    {
        id: "power-walk-form-posture",
        message: "Stand tall, look ahead, and relax your shoulders.",
        priority: 168,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minElapsedSec: 120,
        cooldownSec: 120,
        maxTriggers: 2,
    },
    {
        id: "power-walk-halfway-early",
        message: "You are halfway. Keep the same steady pace.",
        priority: 195,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minWeek: 1,
        maxWeek: 4,
        minDistanceProgress: 45,
        maxDistanceProgress: 60,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-halfway-late",
        message: "Halfway now. Hold your pace and keep moving.",
        priority: 190,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minWeek: 5,
        minDistanceProgress: 45,
        maxDistanceProgress: 60,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-finish-early",
        message: "You are almost done. Keep going. No need to rush.",
        priority: 198,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minWeek: 1,
        maxWeek: 4,
        minDistanceProgress: 85,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-finish-late",
        message: "Almost there. Stay tall and finish at a steady pace.",
        priority: 192,
        triggerOn: ["periodic", "manual"],
        templateIds: ["power_walk"],
        minWeek: 5,
        minDistanceProgress: 85,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-cooldown-early",
        message: "Now we cool down. Slow your pace and let your breathing settle.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["COOL DOWN"],
        minWeek: 1,
        maxWeek: 4,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "power-walk-cooldown-late",
        message: "Now we cool down. Walk easy and let your body relax.",
        priority: 210,
        triggerOn: ["phase_start"],
        templateIds: ["power_walk"],
        phaseLabels: ["COOL DOWN"],
        minWeek: 5,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
];
