import type { RunInstructionRule } from "@/lib/run-instruction-config";

export const WALK_INSTRUCTION_RULES: RunInstructionRule[] = [
    {
        id: "walk-start",
        message: "This is your start. Walk easy and relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["walk"],
        phaseLabels: ["START"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "walk-main",
        message: "Now keep walking. Stay comfortable and keep going.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["walk"],
        phaseLabels: ["BRISK WALK"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "walk-halfway",
        message: "You are doing well. Keep walking easy.",
        priority: 190,
        triggerOn: ["periodic", "manual"],
        templateIds: ["walk"],
        minDistanceProgress: 45,
        maxDistanceProgress: 60,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "walk-finish",
        message: "Almost done. Stay relaxed and keep moving.",
        priority: 195,
        triggerOn: ["periodic", "manual"],
        templateIds: ["walk"],
        minDistanceProgress: 85,
        cooldownSec: 9999,
        maxTriggers: 1,
    },
    {
        id: "walk-cooldown",
        message: "Now slow down. Let your body relax.",
        priority: 220,
        triggerOn: ["phase_start"],
        templateIds: ["walk"],
        phaseLabels: ["COOL DOWN", "SLOW DOWN"],
        cooldownSec: 9999,
        maxTriggers: 1,
    },
];
